name: Ionic CI
on:
  pull_request:
    paths:
      - 'angular-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn run install:frontend
      - run: yarn run start:frontend


